version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py loaddata EmployeeApp/fixtures/admin.json && python manage.py runserver 0.0.0.0:8000"
    container_name: employee_app
    volumes:
      - .:/employee_app
    
    environment:
      - DB_HOST=db
      - DB_NAME=mysql-test
      - DB_USER=user
      - DB_PASS=test
    

  db:
    image: mysql:5.7
    restart: always
    environment:
      - DB_HOST=db
      - DB_NAME=mysql-test
      - DB_USER=user
      - DB_PASS=test

    ports:
      - "3306:3306"
    expose:
      - "3306"

    volumes:
      - db_1:/var/lib/mysql
# Names our volume
volumes:
  db_1:
