# Generated by Django 4.0.3 on 2022-03-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('date_of_graduation', models.DateField()),
                ('date_of_employment', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('salary', models.IntegerField(default=0)),
                ('employee_code', models.CharField(max_length=6)),
                ('supervisors', models.ManyToManyField(blank=True, to='EmployeeApp.employee')),
            ],
        ),
    ]
