# Generated by Django 4.0.3 on 2022-03-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now=True)),
                ('records', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=50)),
                ('errors', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('date_of_graduation', models.DateField(blank=True)),
                ('date_of_employment', models.DateField(blank=True)),
                ('position', models.CharField(max_length=100)),
                ('salary', models.IntegerField(default=0)),
                ('employee_code', models.CharField(blank=True, max_length=6)),
                ('supervisors', models.ManyToManyField(blank=True, to='EmployeeApp.employee')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
