# Generated by Django 4.0.3 on 2022-03-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_graduation',
            field=models.DateField(blank=True),
        ),
    ]
