# Generated by Django 4.0.3 on 2022-03-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_alter_employee_employee_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now=True)),
                ('records', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=50)),
                ('errors', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
